//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT16_SkalochkinFedor_ISP_321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnersImport
    {
        public int IDPartner { get; set; }
        public int TypePartner { get; set; }
        public int TitlePartner { get; set; }
        public int Director { get; set; }
        public int Address { get; set; }
        public long INN { get; set; }
        public int Rating { get; set; }
    
        public virtual Address Address1 { get; set; }
        public virtual Directors Directors { get; set; }
        public virtual Partners Partners { get; set; }
        public virtual PartnerType PartnerType { get; set; }
    }
}
