//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KT16_SkalochkinFedor_ISP_321_MasterFloor.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductsImport
    {
        public int IDProductsImport { get; set; }
        public int TypeProducts { get; set; }
        public int ProductsTitle { get; set; }
        public int Article { get; set; }
        public double MinimalPriceForPartner { get; set; }
    
        public virtual ProductTypeImport ProductTypeImport { get; set; }
        public virtual TitleProducts TitleProducts { get; set; }
    }
}
